# Dockerfile template
FROM ubuntu:18.04
MAINTAINER Sake Pan "enderson.pan@gmail.com"

# Modify the date of this line if you want to refresh the ubuntu install cache
ENV REFRESHED_AT 2019-05-13T15:15:15+08

# Update ubuntu
RUN apt-get -yqq update

# Expose port
#EXPOSE 80
